"""landscapes — the anti-autoreferentiality gate for self-improvement dimensions.

The deepest failure mode of a recursive self-improver is AUTOREFERENTIALITY: improving on a metric/benchmark the
system itself designed, with a resolver that is its own internal score. Such a 'gain' predicts nothing outside
the repo. This module makes the rule explicit and checkable: a performance dimension may enter the MAIN Pareto
vector only if it is anchored OUTSIDE the engine's own judgement.

A dimension declares a `Landscape`; `is_external_landscape(...)` is True only when ALL of these hold:
  • `provenance`               — where the ground truth comes from (a dataset, published equations, conjectures…);
  • `resolver`                 — an EXTERNAL resolver (proof / exhaustive check / held-out data / labels), not a self-score;
  • `ground_truth_independent` — the ground truth was NOT generated by the proposal being measured;
  • `has_negative_control`     — a perturbation that must collapse the gain (else it is measuring leakage);
  • `has_baseline`             — a comparable baseline.

A dimension that fails the gate is `INTERNAL_ONLY`: it may live in diagnostics, but it CANNOT be optimized in the
main Pareto loop. This is what stops the engine from convincing itself it improved.
"""
from __future__ import annotations
from dataclasses import dataclass

EXTERNAL, INTERNAL_ONLY = "EXTERNAL", "INTERNAL_ONLY"


@dataclass
class Landscape:
    name: str
    provenance: str = ""
    resolver: str = ""
    ground_truth_independent: bool = False
    has_negative_control: bool = False
    has_baseline: bool = False

    @property
    def classification(self) -> str:
        return EXTERNAL if self.is_external else INTERNAL_ONLY

    @property
    def is_external(self) -> bool:
        return bool(self.provenance and self.resolver and self.ground_truth_independent
                    and self.has_negative_control and self.has_baseline)

    def missing(self):
        """The anchors a dimension still lacks to be admitted to the main Pareto vector (empty ⇒ external)."""
        out = []
        if not self.provenance:
            out.append("provenance")
        if not self.resolver:
            out.append("external resolver")
        if not self.ground_truth_independent:
            out.append("independent ground truth")
        if not self.has_negative_control:
            out.append("negative control")
        if not self.has_baseline:
            out.append("baseline")
        return out


def is_external_landscape(landscape: Landscape) -> bool:
    """The gate: True iff the dimension is anchored outside the engine's own judgement (admissible in the main
    Pareto vector). A self-scored / self-designed metric returns False → it stays INTERNAL_ONLY."""
    return bool(landscape) and landscape.is_external
